app:
  env: prod
  name: go-mall
  log:
    path: "/tmp/applog/go-mall.log"
    max_size: 100 # 单个日志文件最大100M
    max_age: 60 # 备份文件最多保存60天
  pagination:
    default_size: 20
    max_size: 100
database:
  type: mysql
  master:
    dsn: root:root@tcp(localhost:13316)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000 # 300s 内可复用
  slave:
    dsn: root:root@tcp(localhost:13316)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000